version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db-test
    environment:
      POSTGRES_USER: meuusuario
      POSTGRES_PASSWORD: minhasenha
      POSTGRES_DB: meubanco1
    ports:
      - "5437:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: