spring.application.name=join-sign
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5437/meubanco1
spring.datasource.username=meuusuario
spring.datasource.password=minhasenha

spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

speech.text.chave-api:43c2e8744c144890885c266d2996ef6d
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE